CREATE TABLE people (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document   VARCHAR(14)              NOT NULL,
    name       VARCHAR(100)             NOT NULL,
    surname    VARCHAR(100)             NOT NULL,
    email      VARCHAR(254)             NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_people_document UNIQUE (document),
    CONSTRAINT uk_people_email UNIQUE (email)
);
