CREATE TABLE app_users (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(50)              NOT NULL,
    password   VARCHAR(100)             NOT NULL,
    role       VARCHAR(20)              NOT NULL,
    enabled    BOOLEAN                  NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_app_users_username UNIQUE (username)
);
